export const FETCH_USERS = 'FETCH_USERS';
export const GET_USERS_AUTOCOMPLETE = 'GET_USERS_AUTOCOMPLETE';
export const SET_USERS_AUTOCOMPLETE = 'SET_USERS_AUTOCOMPLETE';
export const RESET_USERS_AUTOCOMPLETE_ACTIVE_ITEMS =
  'RESET_USERS_AUTOCOMPLETE_ACTIVE_ITEMS';
export const MARK_USERS_NEXT_AUTOCOMPLETE = 'MARK_USERS_NEXT_AUTOCOMPLETE';
export const MARK_USERS_PREV_AUTOCOMPLETE = 'MARK_USERS_PREV_AUTOCOMPLETE';
export const SEARCH_USERS = 'SEARCH_USERS';
export const KEEP_USER_SEARCH = 'KEEP_USER_SEARCH';
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
