export const FETCH_USERS = 'FETCH_USERS';
export const GET_USERS_AUTOCOMPLETE = 'GET_USERS_AUTOCOMPLETE';
export const MARK_USERS_NEXT_AUTOCOMPLETE = 'MARK_USERS_NEXT_AUTOCOMPLETE';
export const MARK_USERS_PREV_AUTOCOMPLETE = 'MARK_USERS_PREV_AUTOCOMPLETE';
export const SEARCH_USERS = 'SEARCH_USERS';
